# Generated by Django 6.0.2 on 2026-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_user_status_due',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_unit_due',
        ),
    ]
