# Generated by Django 6.0.2 on 2026-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrears', '0003_arrears_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arrears',
            name='arrears_user_status',
        ),
        migrations.RemoveIndex(
            model_name='arrears',
            name='arrears_invoice_tenant',
        ),
    ]
