# Generated by Django 6.0.2 on 2026-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_model_object',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_user_timestamp',
        ),
    ]
