# Generated by Django 6.0.2 on 2026-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_user_date',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_property_date',
        ),
    ]
