# Generated by Django 6.0.2 on 2026-08-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_created_at_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_documents/id_cards/back/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_documents/id_cards/front/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN: 1 letter, 9 digits, 1 letter (e.g. A123456789B)', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
    ]
