# Generated by Django 6.0.2 on 2026-08-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_created_at_property_updated_at'),
        ('tenants', '0008_tenant_id_card_back_tenant_id_card_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.property'),
        ),
    ]
