# Generated by Django 6.0.2 on 2026-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenance',
            name='maintenance_property_date',
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='maintenance_property_status',
        ),
    ]
